apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: axelar-node-metrics
  namespace: axelar-testnet
  labels:
    app.kubernetes.io/name: axelar
    app.kubernetes.io/component: monitoring
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: axelar
      app.kubernetes.io/component: node
  endpoints:
    - port: prometheus
      path: /metrics
      interval: 30s
      scrapeTimeout: 10s
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: axelar-validator-metrics
  namespace: axelar-testnet
  labels:
    app.kubernetes.io/name: axelar
    app.kubernetes.io/component: monitoring
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: axelar
      app.kubernetes.io/component: validator
  endpoints:
    - port: prometheus
      path: /metrics
      interval: 30s
      scrapeTimeout: 10s
